[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categorias"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

[[main]]
identifier = "sobre"
name = "Sobre"
url = "https://www.cristianoprogramador.com/"
weight = 4
    
# Social Media Configuration
[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/cristianorc"
    weight = 1

[[social]]
    identifier = "youtube"
    name = "Youtube"
    url = "http://www.youtube.com/c/CristianoRaffiCunha"
    weight = 2

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/cristianorc/"
    weight = 3